name: Clang
on: [ push, pull_request ]

jobs:
  linux:
    name: Linux ( Ubuntu )
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        BUILD_TYPE: [ Debug, Release ]
        CLANG: [ 13, 14, 15, 16 ]
    steps:
      - name: Setup toolchain
        uses: egor-tensin/setup-clang@v1
        with:
          version: ${{matrix.CLANG}}

      - name: Install dependencies
        run: |
          pip install conan==1.61.0 gcovr
          sudo apt-get update
          export DISPLAY=:99
          sudo apt-get install -y xvfb libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-util-dev libxcb-util0-dev
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Clone the git repo
        uses: actions/checkout@v3
        with:
          path: project
          fetch-depth: 50

      - name: Create project build directory
        working-directory: project
        run: |
          mkdir build

      - name: Configure project
        working-directory: project
        run: cmake -Bbuild
          -DCMAKE_BUILD_TYPE="${{ matrix.BUILD_TYPE }}"
          -DCMAKE_CXX_COMPILER=clang++-"${{ matrix.CLANG }}" .

      - name: Build project
        working-directory: project
        run: cmake --build ./build --config ${{ matrix.BUILD_TYPE }}  -- -j $(nproc --all)

      - name: Run tests
        working-directory: project/build
        run:
          if [ "${{ matrix.BUILD_TYPE }}" == "Debug" ]; then
          cd tests && ctest -C ${{ matrix.BUILD_TYPE }} --output-on-failure --timeout 540;
          else
          echo "No test on Release Build type";
          fi
