name: GCC
on: [ push, pull_request ]

jobs:
  linux:
    name: Linux ( Ubuntu )
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        BUILD_TYPE: [ Debug, Release ]
        GCC: [ 11, 12, 13]

    steps:
      - name: Install dependencies
        run: |
          pip install conan==1.59.0 gcovr
          sudo add-apt-repository --yes --update ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends g++-${{matrix.gcc}} libudev-dev libgl-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-util-dev libxcb-util0-dev

      - name: Clone the git repo
        uses: actions/checkout@v2
        with:
          path: project
          fetch-depth: 50

      - name: Create project build directory
        working-directory: project
        run: |
          mkdir build

      - name: Configure project
        working-directory: project
        run: cmake -Bbuild
          -DCMAKE_BUILD_TYPE="${{ matrix.BUILD_TYPE }}"
          -DCMAKE_C_COMPILER=gcc-"${{ matrix.GCC }}"
          -DCMAKE_CXX_COMPILER=g++-"${{ matrix.GCC }}" .

      - name: Build project
        working-directory: project
        run: cmake --build ./build --config ${{ matrix.BUILD_TYPE }}  -- -j $(nproc --all)

      - name: Run tests
        working-directory: project/build
        run:
          if [ "${{ matrix.BUILD_TYPE }}" == "Debug" ]; then
          cd tests && ctest -C ${{ matrix.BUILD_TYPE }} --output-on-failure --timeout 540;
          else
          echo "No test on Release Build type";
          fi
